#!/bin/bash

declare -a url=($1)
#printf '%s\n' "${url[@]}"

parsePage () {

  for i in "${url[@]}"
  do
    : 
    output="$(wget -qO- ${i})"
    links="$(echo "$output" | grep -Po '(?<=href=")[^"]*')"
    desiredLinks
    #echo "$links"
  done

}

desiredLinks () {
  Assets1="$(echo "$links" | grep '^/' | grep "\.")"
  Assets2="$(echo "$links" | grep '^./' |  cut -c 2- | grep "\.")"
  Assets3="$(echo "$links" | grep "^$url" | cut -c $((${#url} + 1))- | grep "\." | grep -v "\.com")"
  Assets="$(echo "$Assets1$Assets2$Assets3" | sort | awk '{print "'"$i"'" $0}')"
  printf '\t%s\n' "{"
  printf '\t\t%s%s%s\n' "\"url\": \"" "$i" "\","
  printf '\t\t%s\n' "\"assets\": ["
  IFS=$'\n'
  for j in ""$Assets""
  do
    : 
    printf '\t\t\t%s\n' "$j"
  done
  printf '\t\t%s\n' "]"
  printf '\t%s\n' "}"
  relativeLinks1="$(echo "$links" | grep "^./" | cut -c 2-)"
  relativeLinks2="$(echo "$links" | grep "^/" )"
  regularLinks="$(echo "$links" | grep "^$url" | cut -c $((${#url} + 1))- | grep -v "\." )"
  Rlinks="$(echo "$relativeLinks1$relativeLinks2$regularLinks" | sort | grep -v "\." | awk '{print "'"$i"'" $0}')"
}

removeDuplicates () {
  url="$(echo ${url[@]} | tr [:space:] '\n' | awk '!a[$0]++')"
}

#echo $links
printf '%s\n' "["
parsePage
printf '%s\n' "]"
