#!/bin/bash

desired_links () {
  Assets1="$(echo "$links" | grep '^/' | grep "\.")"
  Assets2="$(echo "$links" | grep '^./' |  cut -c 2- | grep "\.")"
  Assets="$(echo "$Assets1$Assets2" | sort)"
  relative_links_one="$(echo "$links" | grep "^./" | cut -c 2-)"
  relative_links_two="$(echo "$links" | grep "^/" )"
  relative_links="$(echo "$relative_links_one$relative_links_two" | sort | grep -v "\.")"
  regular_links="$(echo "$links" | grep "^http")"
}

parse_page () {

  url=($1)
  output="$(wget -qO- ${url})"
  links="$(echo "$output" | grep -Po '(?<=href=")[^"]*')"
  echo "links"
  #echo "$links"

}

#echo $links
desired_links
